### ISSUE TITLE
Linux build failure (JCuda 9)

### ISSUE THREAD

**Issue by blueberry** [jcuda/jcuda#14]
I'm on freshly updated Arch Linux. Installed Cuda 9.1.85_387.26 (the latest as of today). Relinked gcc to use gcc-6 (that's the last that cuda supports).

Problem 1: JCuda cmake script doesn't find `libnvrtc`. It is similar to https://github.com/jcuda/jcuda/issues/3, with the twist that `libnvrtc` is present in cuda's lib directory, along with the rest of its libraries.

Solution? 1: I edited CMakeCache.txt and replaced CUDA_nvrtc_LIBRARY-NOTFOUND with the actual location of `libnvrtc.so` (`/usr/local/cuda/lib64/libnvrtc.so`). After that, it appears that nvrtc is available, since I am able to continue with the build.

Problem 2: After successfully building `jcuda-parent`, I got the following when i run `mvn clean install` in `jcuda-main`:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JCuda
[INFO] jcuda-common
[INFO] jcuda-natives
[INFO] jcuda
[INFO] jcublas-natives
[INFO] jcublas
[INFO] jcufft-natives
[INFO] jcufft
[INFO] jcurand-natives
[INFO] jcurand
[INFO] jcusparse-natives
[INFO] jcusparse
[INFO] jcusolver-natives
[INFO] jcusolver
[INFO] jnvgraph-natives
[INFO] jnvgraph
[INFO] jcuda-main
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building JCuda 0.9.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-parent ---
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-parent >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-parent <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-parent ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jcuda-parent ---
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda-parent/pom.xml to /home/dragan/.m2/repository/org/jcuda/jcuda-parent/0.9.0/jcuda-parent-0.9.0.pom
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda-common 0.9.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-common ---
[INFO] Deleting /home/dragan/workspace/java/jcuda/jcuda-common/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda-common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jcuda-common ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ jcuda-common ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-sources-jar) @ jcuda-common ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0-sources.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-javadoc-jar) @ jcuda-common ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-common >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-common <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-common ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-common ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jcuda-common ---
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-common/0.9.0/jcuda-common-0.9.0.jar
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda-common/pom.xml to /home/dragan/.m2/repository/org/jcuda/jcuda-common/0.9.0/jcuda-common-0.9.0.pom
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0-sources.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-common/0.9.0/jcuda-common-0.9.0-sources.jar
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda-common/target/jcuda-common-0.9.0-javadoc.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-common/0.9.0/jcuda-common-0.9.0-javadoc.jar
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda-natives 0.9.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-natives ---
[INFO] Deleting /home/dragan/workspace/java/jcuda/jcuda/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda-natives ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda-natives ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda-natives ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda-natives ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jcuda-natives ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ jcuda-natives ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-jar) @ jcuda-natives ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-linux-x86_64.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-sources-jar) @ jcuda-natives ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-sources.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-javadoc-jar) @ jcuda-natives ---
[INFO] Building jar: /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-natives >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-natives <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-natives ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-natives ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jcuda-natives ---
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-natives/0.9.0/jcuda-natives-0.9.0.jar
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda/pom.xml to /home/dragan/.m2/repository/org/jcuda/jcuda-natives/0.9.0/jcuda-natives-0.9.0.pom
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-linux-x86_64.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-natives/0.9.0/jcuda-natives-0.9.0-linux-x86_64.jar
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-sources.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-natives/0.9.0/jcuda-natives-0.9.0-sources.jar
[INFO] Installing /home/dragan/workspace/java/jcuda/jcuda/target/jcuda-natives-0.9.0-javadoc.jar to /home/dragan/.m2/repository/org/jcuda/jcuda-natives/0.9.0/jcuda-natives-0.9.0-javadoc.jar
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda 0.9.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda ---
[INFO] Deleting /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda ---
[INFO] Compiling 141 source files to /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda ---
[INFO] Compiling 12 source files to /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jcuda ---
[INFO] Surefire report directory: /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running jcuda.test.JCudaDriverPrimaryContextTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.608 sec
Running jcuda.test.JCudaPointersToPointerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec
Running jcuda.test.TestPointerToBuffer
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running jcuda.test.JCudaBasicBindingTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.141 sec
Running jcuda.test.JCudaDriverTextureTest
Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: nvcc process exitValue 1
Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: errorMessage:
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004459_00000000-6_JCudaDriverTextureTestKernels.cpp1.ii".

Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: outputMessage:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.145 sec <<< FAILURE!
testTextures(jcuda.test.JCudaDriverTextureTest)  Time elapsed: 0.145 sec  <<< ERROR!
jcuda.CudaException: Could not create ptx file: /usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004459_00000000-6_JCudaDriverTextureTestKernels.cpp1.ii".

	at jcuda.test.JCudaTestUtils.invokeNvcc(JCudaTestUtils.java:132)
	at jcuda.test.JCudaTestUtils.preparePtxFile(JCudaTestUtils.java:39)
	at jcuda.test.JCudaDriverTextureTest.testTextures(JCudaDriverTextureTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running jcuda.test.TestPointerGetByteBuffer
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running jcuda.test.JCudaMemcpy3DTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running jcuda.test.JCudaKernelParamsTest
Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: nvcc process exitValue 1
Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: errorMessage:
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004463_00000000-6_JCudaKernelParamsTestKernel.cpp1.ii".

Dec 15, 2017 3:41:49 PM jcuda.test.JCudaTestUtils invokeNvcc
SEVERE: outputMessage:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.174 sec <<< FAILURE!
testKernelParams(jcuda.test.JCudaKernelParamsTest)  Time elapsed: 0.174 sec  <<< ERROR!
jcuda.CudaException: Could not create ptx file: /usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004463_00000000-6_JCudaKernelParamsTestKernel.cpp1.ii".

	at jcuda.test.JCudaTestUtils.invokeNvcc(JCudaTestUtils.java:132)
	at jcuda.test.JCudaTestUtils.preparePtxFile(JCudaTestUtils.java:39)
	at jcuda.test.JCudaAbstractKernelTest.initialize(JCudaAbstractKernelTest.java:51)
	at jcuda.test.JCudaKernelParamsTest.testKernelParams(JCudaKernelParamsTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running jcuda.test.JCudaDriverMemRangeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.155 sec

Results :

Tests in error: 
  testTextures(jcuda.test.JCudaDriverTextureTest): Could not create ptx file: /usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"(..)
  testKernelParams(jcuda.test.JCudaKernelParamsTest): Could not create ptx file: /usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"(..)

Tests run: 20, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JCuda .............................................. SUCCESS [  0.542 s]
[INFO] jcuda-common ....................................... SUCCESS [  0.344 s]
[INFO] jcuda-natives ...................................... SUCCESS [  0.079 s]
[INFO] jcuda .............................................. FAILURE [  2.775 s]
[INFO] jcublas-natives .................................... SKIPPED
[INFO] jcublas ............................................ SKIPPED
[INFO] jcufft-natives ..................................... SKIPPED
[INFO] jcufft ............................................. SKIPPED
[INFO] jcurand-natives .................................... SKIPPED
[INFO] jcurand ............................................ SKIPPED
[INFO] jcusparse-natives .................................. SKIPPED
[INFO] jcusparse .......................................... SKIPPED
[INFO] jcusolver-natives .................................. SKIPPED
[INFO] jcusolver .......................................... SKIPPED
[INFO] jnvgraph-natives ................................... SKIPPED
[INFO] jnvgraph ........................................... SKIPPED
[INFO] jcuda-main ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.857 s
[INFO] Finished at: 2017-12-15T15:41:49+01:00
[INFO] Final Memory: 27M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jcuda: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jcuda

```

**Comment by blueberry** [comment]
These problems were due to CUDA, and have nothing to do with JCuda.

I managed to solve this by manually patching the offending `floatn.h` file to explicitly check whether `libc` is used with cuda compiler (which is hardcoded to use older gcc) and fix the 128-bit float definition accordingly. After that, the build passed.

For posterity (or the future me), these are the  relevant pages: 
https://devtalk.nvidia.com/default/topic/1023776/-request-add-nvcc-compatibility-with-glibc-2-26/
https://www.reddit.com/r/archlinux/comments/6zrmn1/torch_on_arch/
