### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by Jet132** [jcuda/jcuda#21]
After the last problem ([https://github.com/jcuda/jcuda/issues/20](url)) was fixed, I started optimizing the code and another problem appeared:
```
Exception in thread "main" jcuda.CudaException: CUDA_ERROR_ILLEGAL_ADDRESS
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:337)
	at jcuda.driver.JCudaDriver.cuMemFree(JCudaDriver.java:4022)
	at GPUClasses.GPUAI.layer(GPUAI.java:95)
	at GPUClasses.GPUAI.run(GPUAI.java:70)
	at AI_Engine.AIEngine.runEngine(AIEngine.java:122)
	at Main.MainGameLoop.run(MainGameLoop.java:68)
	at Main.MainGameLoop.main(MainGameLoop.java:48)

```
The strange thing is also, that it doesn't occure on the first few "runs", it only comes after exactly `1525970000000` millisecounds, that's about 25'000 calles of ```run()``` (look at the code below).
Also only if it needs to calculate with an array of about the lenght 200.

To explain my changes, I first need to tell what the program actually should do.
If your familiar with neural networks, you will know that they have layers, which contain weights and baises.
You pass a input to the network and it gets passed through every layer (input*weights+baises) and the weights and baises don't change most of the time. 
So I made that those two are permenant on the gpu and only get exchanged if they get changed. Also i made so, that every output (except the last one) stays on the gpu so the next layer can directly use it.

here is the important code (exeption lines are marked with **//ERROR** and have the same exeption):
```
        private CUdeviceptr[] weightPointers;
	private CUdeviceptr[] baisesPointers;
	private CUdeviceptr temp;//the output of last layer

	public GPUAI(int Generationsteps, int[] layout) {

		weightPointers = new CUdeviceptr[weights.length];
		for (int i = 0; i < weights.length; i++) {
			weightPointers[i] = new CUdeviceptr();
			cuMemAlloc(weightPointers[i], weights[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(weightPointers[i], Pointer.to(weights[i]), weights[i].length * Sizeof.FLOAT);
		}

		baisesPointers = new CUdeviceptr[baises.length];
		for (int i = 0; i < baises.length; i++) {
			baisesPointers[i] = new CUdeviceptr();
			cuMemAlloc(baisesPointers[i], baises[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(baisesPointers[i], Pointer.to(baises[i]), baises[i].length * Sizeof.FLOAT);
		}
	}

	public void run() {
		temp = new CUdeviceptr();
		cuMemAlloc(temp, Inputs.length * Sizeof.FLOAT);
		cuMemcpyHtoD(temp, Pointer.to(Inputs), Inputs.length * Sizeof.FLOAT);

		int last_layer = Inputs.length;
		for (int i = 0; i < weights.length-1; i++) {

			layer(i, last_layer);
			last_layer = baises[i].length;
		}
		Outputs = final_layer(weights.length-1, last_layer);
	}

	void layer(int layer, int inputsize) {
		// Allocate device output memory
		CUdeviceptr deviceOutput = new CUdeviceptr();
		cuMemAlloc(deviceOutput, baises.length * Sizeof.FLOAT);
		// Set up the kernel parameters: A pointer to an array
		// of pointers which point to the actual values.
		Pointer kernelParameters = Pointer.to(
                                Pointer.to(new int[] { inputsize }),
				Pointer.to(new int[] { baises[layer].length }),
                                Pointer.to(temp), 
                                Pointer.to(weightPointers[layer]),
				Pointer.to(baisesPointers[layer]), 
                                Pointer.to(deviceOutput));

		// Call the kernel function.
		int blockSizeX = 1000;
		int gridSizeX = (int) Math.ceil((double) baises.length / blockSizeX);
		cuLaunchKernel(AIEngine.LayerFunction, 
                                gridSizeX, 1, 1, // Grid dimension
				blockSizeX, 1, 1, // Block dimension
				0, null, // Shared memory size and stream
				kernelParameters, null // Kernel- and extra parameters
		);

                cuMemFree(temp); //ERROR
		temp = deviceOutput;

	}

	float[] final_layer(int layer, int inputsize) {
		// Allocate device output memory
		CUdeviceptr deviceOutput = new CUdeviceptr();
		cuMemAlloc(deviceOutput, baises.length * Sizeof.FLOAT);
		// Set up the kernel parameters: A pointer to an array
		// of pointers which point to the actual values.
		Pointer kernelParameters = Pointer.to(
                                Pointer.to(new int[] { inputsize }),
				Pointer.to(new int[] { baises[layer].length }), 
                                Pointer.to(temp), 
                                Pointer.to(weightPointers[layer]),
				Pointer.to(baisesPointers[layer]), 
                                Pointer.to(deviceOutput));

		// Call the kernel function.
		int blockSizeX = 1024;
		int gridSizeX = (int) Math.ceil((double) baises.length / blockSizeX);
		cuLaunchKernel(AIEngine.LayerFunction, 
                                gridSizeX, 1, 1, // Grid dimension
				blockSizeX, 1, 1, // Block dimension
				0, null, // Shared memory size and stream
				kernelParameters, null // Kernel- and extra parameters
		);

		

		float hostOutput[] = new float[baises.length];
		cuMemcpyDtoH(Pointer.to(hostOutput), deviceOutput, baises.length * Sizeof.FLOAT); //ERROR
		
		cuMemFree(temp); //ERROR
		
		return hostOutput;
	}

	void setWeights(float[][] weights) {
		for (int i = 0; i < weightPointers.length; i++) {
			cuMemFree(weightPointers[i]);
		}
		weightPointers = new CUdeviceptr[weights.length];
		for (int i = 0; i < weights.length; i++) {
			weightPointers[i] = new CUdeviceptr();
			cuMemAlloc(weightPointers[i], weights[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(weightPointers[i], Pointer.to(weights[i]), weights[i].length * Sizeof.FLOAT);
		}
	}

	void setBaises(float[][] baises) {
		for (int i = 0; i < baisesPointers.length; i++) {
			cuMemFree(baisesPointers[i]);
		}
		baisesPointers = new CUdeviceptr[baises.length];
		for (int i = 0; i < baises.length; i++) {
			baisesPointers[i] = new CUdeviceptr();
			cuMemAlloc(baisesPointers[i], baises[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(baisesPointers[i], Pointer.to(baises[i]), baises[i].length * Sizeof.FLOAT);
		}
	}
```

**Comment by jcuda** [comment]
Form skimming **very** quickly over the code, it seems like `temp` is created and allocated in the `run` method, but freed multiple times (namely, in each call to `layer`). Beyond that: If I should try this out, I'd appreciate a compileable example (but even then I cannot promise that I can allocate the time for debugging it, *unless* you suspect a bug in JCuda).

**Comment by Jet132** [comment]
Here is the whole code: [https://github.com/Jet132/temp/tree/master/AI_Engine_6.2/src](url)

- setup of Context and Function: [https://github.com/Jet132/temp/blob/master/AI_Engine_6.2/src/AI_Engine/AIEngine.java](url) in GPUsetup() 

- Exeption code: [https://github.com/Jet132/temp/blob/master/AI_Engine_6.2/src/GPUClasses/GPUAI.java](url)

You mentioned that temp gets freed from memory multiple time. That's because I intented, that the old input/output gets freed so that temp can get set to the new output which is exactly a line beneath.
```
cuMemFree(temp); 
temp = deviceOutput;
```
maybe I'm coping the pointer wrong, but as I said in the first comment, it works until it somehow stops.

**Comment by Jet132** [comment]
I went over the code again and noticed that I allocated the wrong amount of memory and also calculated the gridsize and blocksize ratio wrong.
Instead of using `baises[layer].length`, to get number of neurons in a layer, I used `baises.length` and got the number of layers.

But still thanks for your time!
I will close this issue
