### ISSUE TITLE
jar missing

### ISSUE THREAD

**Issue by Session-gao** [jcuda/jcuda#22]
Dear 👍
     I used the latest version, but the error was reported when running. The specific error was as follows:

` ava.lang.UnsatisfiedLinkError: Error while loading native library "JCudaDriver-
0.9.0d-linux-x86_64"
Operating system name: Linux
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaDriver-0.9.0d-linux-x86_64 in java.libra
ry.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
        at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:296)
        at com.alibaba.datax.common.jcuda.JCUDAOperation.<clinit>(JCUDAOperation
.java:30)
        at com.alibaba.datax.common.statistics.VMInfo.<init>(VMInfo.java:26)
        at com.alibaba.datax.common.statistics.VMInfo.getVmInfo(VMInfo.java:36)
        at com.alibaba.datax.core.Engine.entry(Engine.java:160)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
Stack trace from the attempt to load the library as a resource:
java.lang.UnsatisfiedLinkError: /tmp/libJCudaDriver-0.9.0d-linux-x86_64.so 

: libc
uda.so 

.1: 鏃犳硶鎵撳紑?叡浜璞℃枃浠? 娌℃湁閭ｄ釜鏂囦欢鎴栫洰褰?
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at jcuda.LibUtils.loadLibraryResource(LibUtils.java:260)
        at jcuda.LibUtils.loadLibrary(LibUtils.java:158)
        at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:296)
        at com.alibaba.datax.common.jcuda.JCUDAOperation.<clinit>(JCUDAOperation
.java:30)
        at com.alibaba.datax.common.statistics.VMInfo.<init>(VMInfo.java:26)
        at com.alibaba.datax.common.statistics.VMInfo.getVmInfo(VMInfo.java:36)
        at com.alibaba.datax.core.Engine.entry(Engine.java:160)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
---(end of nested stack traces)---

        at jcuda.LibUtils.loadLibrary(LibUtils.java:193)
        at jcuda.driver.JCudaDriver.<clinit>(JCudaDriver.java:296)
        at com.alibaba.datax.common.jcuda.JCUDAOperation.<clinit>(JCUDAOperation
.java:30)
        at com.alibaba.datax.common.statistics.VMInfo.<init>(VMInfo.java:26)
        at com.alibaba.datax.common.statistics.VMInfo.getVmInfo(VMInfo.java:36)
        at com.alibaba.datax.core.Engine.entry(Engine.java:160)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
#`   
However, I didn't find the jar online
i need help !

**Comment by jcuda** [comment]
The file `libJCudaDriver-0.9.0d-linux-x86-64.so` should be contained in the `jcuda-natives-0.9.0d-linux-x86_64.jar` JAR file. This JAR file should automatically be discovered by Maven, as a dependency of the `jcuda-0.9.0d.jar` file. You can find the Maven artifact at https://search.maven.org/#search|ga|1|g%3A%22org.jcuda%22%20AND%20a%3A%22jcuda-natives%22 

The JAR file with the native library is also contained in the download package at http://www.jcuda.org/downloads/JCuda-All-0.9.0d-bin-x86_64.zip 

If you are using JCuda manually (i.e. without Maven), then the file `jcuda-natives-0.9.0d-linux-x86_64.jar` has to be added to the `classpath`.

By the way, as a possible hint for what might be wrong here: What does 

> 鏃犳硶鎵撳紑?叡浜璞℃枃浠? 娌℃湁閭ｄ釜鏂囦欢鎴栫洰褰?

mean?

**Comment by Session-gao** [comment]
![image](https://user-images.githubusercontent.com/28760899/40893744-7699f54a-67d6-11e8-97c1-5e712117074a.png)
No, the jar has been packaged into the directory and the error should be there:
java.lang.UnsatisfiedLinkError: no JCudaDriver-0.9.0d-linux-x86_64 in java.libra
ry.path       
Please ignore my use of different versions

**Comment by jcuda** [comment]
The relevant part is actually the one that starts at

> Stack trace from the attempt to load the library as a resource:
> java.lang.UnsatisfiedLinkError: /tmp/libJCudaDriver-0.9.0d-linux-x86_64.so

The library from the JAR should be unpacked to the temporary directory, and loaded from there.

**Comment by jcuda** [comment]
Could it be that you did not install the CUDA version for the respective JCuda version? Note that the version numbers should match, as in CUDA 8.0 and JCuda 0.8.0, or CUDA 9.0 and JCuda 0.9.0d

Otherwise, without further information, I'd close this.
